export const monthlyLabels = {
  en: {
    title: 'Monthly Series',
    name: 'The Noble Life',
    arabic: 'السِّيرَة النَّبَوِيَّة',
    intro: 'A little longer to listen. A little more space to reflect. A monthly audio journey through the life of Prophet Muhammad ﷺ, in English and Urdu.',
    invitation: 'Discover the monthly journey',
    format: 'Planned format: around 15 minutes per episode, in each language.',
    preparing: 'First episode in preparation',
    firstTitle: 'Before his birth',
    firstDetail: 'Our opening episode is being researched: the events and context before the birth of Prophet Muhammad ﷺ. Its scope will follow the evidence.',
    review: 'Episodes appear here only after their sources, scripts and recordings have been reviewed and approved. No release date has been announced.',
    archive: 'Episode archive',
    empty: 'No episodes published yet.',
    emptyDetail: 'While the first monthly episode takes shape, explore the existing narrated books.',
    books: 'Explore the audiobooks',
    back: 'All monthly episodes',
    unavailable: 'Episode not available',
    unavailableDetail: 'This episode has not been published here. Return to the archive to see what is available.',
    sources: 'Sources & qualifications',
    transcript: 'Episode transcript',
    editorial: 'An original editorial narrative, not a single hadith or a historical recording.',
    released: 'Published',
    open: 'Open episode',
    paused: 'Pause ornament motion',
    resumeMotion: 'Resume ornament motion',
    reduced: 'Reduced motion',
  },
  ur: {
    title: 'ماہانہ سلسلہ',
    name: 'سیرتِ نبوی ﷺ',
    arabic: 'السِّيرَة النَّبَوِيَّة',
    intro: 'سننے کے لیے کچھ زیادہ وقت، غور و فکر کے لیے کچھ زیادہ فرصت۔ نبی کریم ﷺ کی حیاتِ مبارکہ پر انگریزی اور اردو میں ایک ماہانہ صوتی سلسلہ۔',
    invitation: 'ماہانہ سلسلہ دیکھیں',
    format: 'مجوزہ ترتیب: ہر زبان میں ہر قسط تقریباً پندرہ منٹ کی ہوگی۔',
    preparing: 'پہلی قسط کی تیاری جاری ہے',
    firstTitle: 'ولادت سے پہلے',
    firstDetail: 'پہلی قسط کے لیے نبی کریم ﷺ کی ولادت سے پہلے کے واقعات اور حالات پر تحقیق جاری ہے۔ موضوع کی تفصیل دستیاب شواہد کے مطابق ہوگی۔',
    review: 'ہر قسط مآخذ، متن اور آڈیو کے جائزے اور منظوری کے بعد یہاں شائع ہوگی۔ ابھی اشاعت کی تاریخ طے نہیں کی گئی۔',
    archive: 'شائع شدہ اقساط',
    empty: 'ابھی کوئی قسط شائع نہیں ہوئی۔',
    emptyDetail: 'پہلی ماہانہ قسط کی تیاری کے دوران موجودہ آڈیو بکس سے استفادہ کریں۔',
    books: 'آڈیو بکس دیکھیں',
    back: 'تمام ماہانہ اقساط',
    unavailable: 'قسط دستیاب نہیں',
    unavailableDetail: 'یہ قسط یہاں شائع نہیں ہوئی۔ دستیاب اقساط کے لیے فہرست پر واپس جائیں۔',
    sources: 'مآخذ اور ضروری وضاحتیں',
    transcript: 'قسط کا تحریری متن',
    editorial: 'یہ ایک اصل ادارتی بیانیہ ہے، کوئی ایک حدیث یا تاریخی ریکارڈنگ نہیں۔',
    released: 'تاریخِ اشاعت',
    open: 'قسط کھولیں',
    paused: 'آرائشی حرکت روکیں',
    resumeMotion: 'آرائشی حرکت بحال کریں',
    reduced: 'کم حرکت',
  },
} as const
