export const topicsLabels = {
  en: {
    title: 'Thoughts & Topics',
    name: 'Thoughts & Topics',
    arabic: 'مَوْضُوعَات',
    intro: 'Single subjects, followed carefully. Longer audio reflections on themes from the life and teaching of Prophet Muhammad ﷺ, in English and Urdu.',
    invitation: 'Explore thoughts & topics',
    format: 'Format: one subject per edition, around twenty minutes in each language.',
    preparing: 'First topic in preparation',
    firstTitle: 'A first subject',
    firstDetail: 'The opening topic is being researched. Its scope will follow the evidence.',
    review: 'Topics appear here only after their sources, scripts and recordings have been reviewed and approved.',
    archive: 'Published topics',
    empty: 'No topics published yet.',
    emptyDetail: 'While the first topic takes shape, explore the existing narrated books.',
    books: 'Explore the audiobooks',
    back: 'All topics',
    unavailable: 'Topic not available',
    unavailableDetail: 'This topic has not been published here. Return to the list to see what is available.',
    sources: 'Sources & qualifications',
    transcript: 'Topic transcript',
    editorial: 'An original editorial narrative, not a single hadith or a historical recording.',
    released: 'Published',
    open: 'Open topic',
    paused: 'Pause ornament motion',
    resumeMotion: 'Resume ornament motion',
    reduced: 'Reduced motion',
  },
  ur: {
    title: 'مضامین و موضوعات',
    name: 'مضامین و موضوعات',
    arabic: 'مَوْضُوعَات',
    intro: 'ایک موضوع، پوری توجہ کے ساتھ۔ نبی کریم ﷺ کی حیات اور تعلیمات کے موضوعات پر انگریزی اور اردو میں تفصیلی صوتی مضامین۔',
    invitation: 'مضامین و موضوعات دیکھیں',
    format: 'ترتیب: ہر اشاعت ایک موضوع پر، ہر زبان میں تقریباً بیس منٹ۔',
    preparing: 'پہلے موضوع کی تیاری جاری ہے',
    firstTitle: 'پہلا موضوع',
    firstDetail: 'پہلے موضوع پر تحقیق جاری ہے۔ اس کی تفصیل دستیاب شواہد کے مطابق ہوگی۔',
    review: 'ہر موضوع مآخذ، متن اور آڈیو کے جائزے اور منظوری کے بعد یہاں شائع ہوگا۔',
    archive: 'شائع شدہ موضوعات',
    empty: 'ابھی کوئی موضوع شائع نہیں ہوا۔',
    emptyDetail: 'پہلے موضوع کی تیاری کے دوران موجودہ آڈیو بکس سے استفادہ کریں۔',
    books: 'آڈیو بکس دیکھیں',
    back: 'تمام موضوعات',
    unavailable: 'موضوع دستیاب نہیں',
    unavailableDetail: 'یہ موضوع یہاں شائع نہیں ہوا۔ دستیاب موضوعات کے لیے فہرست پر واپس جائیں۔',
    sources: 'مآخذ اور ضروری وضاحتیں',
    transcript: 'موضوع کا تحریری متن',
    editorial: 'یہ ایک اصل ادارتی بیانیہ ہے، کوئی ایک حدیث یا تاریخی ریکارڈنگ نہیں۔',
    released: 'تاریخِ اشاعت',
    open: 'موضوع کھولیں',
    paused: 'آرائشی حرکت روکیں',
    resumeMotion: 'آرائشی حرکت بحال کریں',
    reduced: 'کم حرکت',
  },
} as const
