import { join } from 'node:path'
import { expect, test } from './fixtures.ts'

test('monthly section is reachable from home, navigation and audiobooks without publishing drafts', async ({ page }, testInfo) => {
  const audioRequests: string[] = []
  page.on('request', (request) => { if (/\/audio\/.*\.mp3/.test(request.url())) audioRequests.push(request.url()) })
  await page.goto('./?lang=en')
  await page.getByRole('button', { name: 'Discover the monthly journey', exact: true }).click()
  await expect(page).toHaveURL(/view=monthly/)
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Monthly Series')
  await expect(page.getByRole('link', { name: /^Monthly Series/ })).toHaveAttribute('aria-current', 'page')
  await expect(page.getByRole('heading', { level: 3, name: /Before His Birth/ })).toBeVisible()
  await expect(page.getByText('First episode in preparation', { exact: true })).toHaveCount(0)
  await expect(page.locator('.monthly-player')).toHaveCount(0)
  await expect(page.locator('audio')).toHaveCount(1)
  expect(await page.locator('audio').evaluate((element) => element.paused)).toBe(true)
  expect(audioRequests).toEqual([])
  if (process.env.MONTHLY_ARTIFACTS) {
    await page.evaluate(() => document.fonts.ready)
    await page.screenshot({ path: join(process.env.MONTHLY_ARTIFACTS, `monthly-archive-${testInfo.project.name}.png`), fullPage: true })
  }
  await page.getByRole('button', { name: 'Explore the audiobooks', exact: true }).click()
  await expect(page.locator('.audiobook-card')).toHaveCount(3)
  await page.getByRole('button', { name: 'Discover the monthly journey', exact: true }).click()
  await page.goBack()
  await expect(page).toHaveURL(/view=audiobooks/)
  await page.getByRole('link', { name: /^Monthly Series/ }).click()
  await page.reload()
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Monthly Series')
})

test('monthly Urdu, dark mode and reduced motion preserve layout and honest unavailable links', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('./?view=monthly&lang=ur&scoutTheme=dark')
  await expect(page.locator('html')).toHaveAttribute('dir', 'rtl')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('ماہانہ سلسلہ')
  await expect(page.getByRole('button', { name: 'کم حرکت', exact: true })).toBeDisabled()
  await page.evaluate(() => document.fonts.ready)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'English', exact: true }).click()
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Monthly Series')
  await page.goto('./?view=monthly&episode=unpublished-draft&lang=en')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Episode not available')
  await expect(page.locator('.monthly-player')).toHaveCount(0)
  await page.getByRole('button', { name: 'All monthly episodes', exact: true }).click()
  await expect(page).not.toHaveURL(/episode=/)
  await expect(page.getByRole('heading', { level: 3, name: /Before His Birth/ })).toBeVisible()
})

test('monthly decorative pause is persistent and navigation fits narrow screens', async ({ page }) => {
  await page.goto('./?view=monthly&lang=en')
  await page.getByRole('button', { name: 'Pause ornament motion', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-motion', 'paused')
  await page.reload()
  await expect(page.getByRole('button', { name: 'Resume ornament motion', exact: true })).toHaveAttribute('aria-pressed', 'true')
  for (const width of [360, 768, 1024]) {
    await page.setViewportSize({ width, height: 900 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await expect(page.getByRole('link', { name: /^Monthly Series/ })).toBeInViewport()
  }
})

test('published monthly editions use the saved recordings, accurate durations, chapter markers and long resume', async ({ page }, testInfo) => {
  await page.goto('./?view=monthly&episode=monthly-life-001&lang=en')
  await expect(page.locator('.book-facts')).toContainText('9:58')
  await expect(page.locator('.book-facts')).toContainText('English · abridged edition')
  await expect(page.locator('.book-chapter')).toHaveCount(9)
  await expect(page.locator('.monthly-sources a')).toHaveCount(4)
  const audio = page.locator('audio')
  expect(await audio.evaluate((element) => element.paused)).toBe(true)
  await page.getByRole('combobox', { name: 'Audio language', exact: true }).selectOption('ur')
  await expect(page.locator('.book-facts')).toContainText('11:47')
  await expect(page.locator('.book-chapter')).toHaveCount(10)
  await expect(page.locator('.monthly-sources a')).toHaveCount(7)
  await page.getByRole('button', { name: 'Start listening', exact: true }).click()
  await expect.poll(() => audio.evaluate((element) => element.duration)).toBeGreaterThan(706)
  await audio.evaluate((element) => { element.muted = true; element.currentTime = 650 })
  await page.locator('.monthly-player').getByRole('button', { name: 'Pause', exact: true }).click()
  await page.reload()
  expect(await audio.evaluate((element) => element.paused)).toBe(true)
  await page.getByRole('button', { name: 'Continue listening', exact: true }).click()
  await expect.poll(() => audio.evaluate((element) => element.currentTime)).toBeGreaterThanOrEqual(649)
  await page.locator('.monthly-player').getByRole('button', { name: 'Pause', exact: true }).click()
  await page.getByRole('combobox', { name: 'Narration language', exact: true }).selectOption('en')
  await expect(page.locator('.book-chapter')).toHaveCount(9)
  await page.locator('.book-chapter[data-section="7"]').click()
  await expect.poll(() => audio.evaluate((element) => element.currentTime)).toBeGreaterThan(480)
  await expect(page.locator('.book-chapter[data-section="7"]')).toHaveAttribute('aria-current', 'step')
  await page.locator('.monthly-player').getByRole('button', { name: 'Pause', exact: true }).click()
  await page.locator('.monthly-transcripts summary').first().click()
  await expect(page.locator('.monthly-transcripts details').first()).toContainText('Welcome to The Noble Life')
  await expect(audio).toHaveCount(1)
  await page.evaluate(() => document.fonts.ready)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  if (process.env.MONTHLY_ARTIFACTS) await page.screenshot({ path: join(process.env.MONTHLY_ARTIFACTS, `monthly-published-${testInfo.project.name}.png`), fullPage: true })
})

test('NEW badge expires and updates after returning to an open monthly page', async ({ page }) => {
  await page.clock.setFixedTime(new Date('2026-09-21T08:00:00Z'))
  await page.goto('./?view=monthly&lang=en')
  await expect(page.locator('.primary-nav .monthly-new')).toHaveText('NEW')
  await expect(page.locator('.monthly-archive .monthly-new')).toHaveCount(1)
  await expect(page.locator('.monthly-archive li').first()).toContainText('Birth, Family and Early Childhood')
  await page.clock.setFixedTime(new Date('2026-10-21T00:00:00Z'))
  await page.evaluate(() => window.dispatchEvent(new Event('focus')))
  await expect(page.locator('.monthly-new')).toHaveCount(0)
})

test('the second episode plays complete parallel editions and keeps the first episode reachable', async ({ page }) => {
  await page.goto('./?view=monthly&episode=monthly-life-002&lang=en')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Birth, Family and Early Childhood')
  await expect(page.locator('.book-facts')).toContainText('7:41')
  await expect(page.locator('.book-facts')).toContainText('English · full edition')
  await expect(page.locator('.book-chapter')).toHaveCount(8)
  await expect(page.locator('.monthly-sources a')).toHaveCount(5)
  await expect(page.locator('.monthly-sources a[href^="https://www.britannica.com"]')).toHaveCount(1)
  await page.getByRole('combobox', { name: 'Audio language', exact: true }).selectOption('ur')
  await expect(page.locator('.book-facts')).toContainText('8:56')
  await expect(page.locator('.book-chapter')).toHaveCount(8)
  await page.goto('./?view=monthly&episode=monthly-life-001&lang=en')
  await expect(page.locator('.book-facts')).toContainText('9:58')
})
